image: python:3.8

before_script:
  - python -m pip install --upgrade pip
  - pip install flake8 pytest
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

pytest:
  stage: test
  script:
    - pytest
